name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Private Registry
      uses: docker/login-action@v1
      with:
        registry: registrydocker.robiche.fr:443
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./build
        file: ./build/Dockerfile
        push: true
        tags: registrydocker.robiche.fr:443/rustdesk-api-server:latest

    - name: Docker Logout
      run: docker logout registrydocker.robiche.fr:443
