name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Private Registry
      run: echo "${{ secrets.REGISTRY_SECRET }}" | docker login https://registry.robiche.fr:443 --username unused --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./build
        file: ./build/Dockerfile
        push: true
        tags: registry.robiche.fr/rustdesk-api-server:latest

    - name: Docker Logout
      run: docker logout ${{ secrets.REGISTRY_URL }}
